Notes Differences
* R indexes from 1, Python 0
* R the function surrounds the data, while in Python, you add it to the end
    * R count(df)
    * Python df.count()

In [ ]:
#pip install rpy2

In [1]:
%load_ext rpy2.ipython

Error importing in API mode: ImportError("dlopen(/Users/jebbonanno/opt/anaconda3/lib/python3.9/site-packages/_rinterface_cffi_api.abi3.so, 0x0002): symbol not found in flat namespace '_R_BaseEnv'")
Trying to import in ABI mode.

In [2]:
import pandas as pd
import numpy as np

#R transfer
import rpy2.robjects as robjects
from rpy2.robjects import pandas2ri
pandas2ri.activate()

DeprecationWarning:
The activate and deactivate are deprecated. To set a conversion
context check the docstring for rpy2.robjects.conversion.Converter.context.

In [3]:
%%R
# Install once; comment out after the first run
#install.packages("hellodatascience", repos = "https://cloud.r-project.org")
#install.packages("skimr", repos = "https://cloud.r-project.org")

library(hellodatascience)
library(skimr)

data(planets)
head(planets)

# A tibble: 6 × 7
  name        mass length_of_day mean_temp n_moons ring_system surface_pressure
  <chr>      <dbl>         <dbl> <fct>       <int> <lgl>                  <dbl>
1 Mercury    0.33         4223.  positive        0 FALSE                   0
2 Venus      4.87         2802   positive        0 FALSE                  92
3 Earth      5.97           24   positive        1 FALSE                   1
4 Mars       0.642          24.7 negative        2 FALSE                   0.01
5 Jupiter 1898               9.9 negative       95 TRUE                   NA
6 Saturn   568              10.7 negative      146 TRUE                   NA

In [4]:
planets_python = robjects.r['planets']
# convert to pandas
planets_df = pandas2ri.rpy2py(planets_python)

### Head

In [5]:
%%R 

head(planets)

# A tibble: 6 × 7
  name        mass length_of_day mean_temp n_moons ring_system surface_pressure
  <chr>      <dbl>         <dbl> <fct>       <int> <lgl>                  <dbl>
1 Mercury    0.33         4223.  positive        0 FALSE                   0
2 Venus      4.87         2802   positive        0 FALSE                  92
3 Earth      5.97           24   positive        1 FALSE                   1
4 Mars       0.642          24.7 negative        2 FALSE                   0.01
5 Jupiter 1898               9.9 negative       95 TRUE                   NA
6 Saturn   568              10.7 negative      146 TRUE                   NA

In [6]:
planets_df.head()

,name,mass,length_of_day,mean_temp,n_moons,ring_system,surface_pressure
1,Mercury,0.330,4222.6,2,0,False,0.00
2,Venus,4.870,2802.0,2,0,False,92.00
3,Earth,5.970,24.0,2,1,False,1.00
4,Mars,0.642,24.7,1,2,False,0.01
5,Jupiter,1898.000,9.9,1,95,True,NaN

In [7]:
### Mean

In [8]:
%%R
mean(planets$n_moons)

[1] 36

In [9]:
planets_df['n_moons'].mean()

36.0

In [10]:
### Quartiles

In [11]:
%%R
quantile(planets$n_moons, probs = c(.25, .50, .75))

  25%   50%   75%
 0.75  9.00 44.75

In [12]:
planets_df['n_moons'].quantile(q=[.25,.50,.75])

0.25     0.75
0.50     9.00
0.75    44.75
Name: n_moons, dtype: float64

In [13]:
%%R
summary(planets)

        name        mass          length_of_day        mean_temp
 Length   :8   Min.   :   0.330   Min.   :   9.90   negative:5
 N.unique :8   1st Qu.:   3.813   1st Qu.:  14.75   positive:3
 N.blank  :0   Median :  46.385   Median :  20.60
 Min.nchar:4   Mean   : 333.327   Mean   : 890.90
 Max.nchar:7   3rd Qu.: 218.500   3rd Qu.: 719.02
               Max.   :1898.000   Max.   :4222.60

    n_moons       ring_system     surface_pressure
 Min.   :  0.00   Mode :logical   Min.   : 0.0000
 1st Qu.:  0.75   FALSE:4         1st Qu.: 0.0075
 Median :  9.00   TRUE :4         Median : 0.5050
 Mean   : 36.00                   Mean   :23.2525
 3rd Qu.: 44.75                   3rd Qu.:23.7500
 Max.   :146.00                   Max.   :92.0000
                                  NAs    :4

In [17]:
%%R
skimr::skim(planets)

── Data Summary ────────────────────────
                           Values
Name                       planets
Number of rows             8
Number of columns          7
_______________________
Column type frequency:
  character                1
  factor                   1
  logical                  1
  numeric                  4
________________________
Group variables            None

── Variable type: character ────────────────────────────────────────────────────
  skim_variable n_missing complete_rate min max empty n_unique whitespace
1 name                  0             1   4   7     0        8          0

── Variable type: factor ───────────────────────────────────────────────────────
  skim_variable n_missing complete_rate ordered n_unique top_counts
1 mean_temp             0             1 FALSE          2 neg: 5, pos: 3

── Variable type: logical ──────────────────────────────────────────────────────
  skim_variable n_missing complete_rate mean count
1 ring_system           0             1  0.5 FAL: 4, TRU: 4

── Variable type: numeric ──────────────────────────────────────────────────────
  skim_variable    n_missing complete_rate  mean     sd   p0     p25    p50
1 mass                     0           1   333.   661.  0.33  3.81   46.4
2 length_of_day            0           1   891.  1662.  9.9  14.8    20.6
3 n_moons                  0           1    36     54.8 0     0.75    9
4 surface_pressure         4           0.5  23.3   45.8 0     0.0075  0.505
    p75  p100 hist
1 218.  1898  ▇▁▁▁▁
2 719.  4223. ▇▁▁▁▁
3  44.8  146  ▇▁▁▁▁
4  23.8   92  ▇▁▁▁▂

In [16]:
planets_df.describe()

              mass  length_of_day  mean_temp     n_moons  surface_pressure
count     8.000000        8.00000   8.000000    8.000000          4.000000
mean    333.326500      890.90000   1.375000   36.000000         23.252500
std     660.538057     1661.92169   0.517549   54.795725         45.834067
min       0.330000        9.90000   1.000000    0.000000          0.000000
25%       3.813000       14.75000   1.000000    0.750000          0.007500
50%      46.385000       20.60000   1.000000    9.000000          0.505000
75%     218.500000      719.02500   2.000000   44.750000         23.750000
max    1898.000000     4222.60000   2.000000  146.000000         92.000000

In [ ]:
### Null Values

In [18]:
%%R
mean(planets$surface_pressure, na.rm = TRUE) #Remove NA is not true by default

mean(planets$surface_pressure

[1] 23.2525

In [20]:
planets_df['surface_pressure'].mean() #skip_na is true by default

23.2525